# Site Settings
title: Vulcana Cinema
email: vulcanacinema@gmail.com
description: >-
  Vulcana Cinema é uma produtora brasileira focada em cinema de autor, primeiros longas e no mercado internacional.
address: |+
  Rua Castro Alves, 163  
  Porto Alegre, RS — Brasil

baseurl: ""
url: "https://vulcanacinema.com"

lang: pt-BR
logo: "/assets/images/logo.png"

# Build settings
markdown: kramdown

include:
  - _headers

collections:
  projects:
    output: true
    permalink: "/projects/:title/"

defaults:
  - scope:
      path: ""
    values:
      lang: "pt-BR"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "_projects/en"
      type: "projects"
    values:
      lang: "en"
  - scope:
      path: "en"
    values:
      lang: "en"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus

social:
  name: Vulcana Cinema
  links:
    - https://www.instagram.com/vulcanacinema
    - https://vimeo.com/vulcanacinema
