# Site Settings
title: Vulcana Cinema
email: vulcanacinema@gmail.com
description: >-
  Vulcana Cinema é uma produtora brasileira focada em cinema de autor, primeiros longas e mercado internacional.

baseurl: ""
url: "https://www.vulcanacinema.com"

lang: pt
logo: "/assets/images/logo.svg"

collections:
  projects:
    output: true
    permalink: "/:lang/:category/:title/"

# Build settings
markdown: kramdown
permalink: "/:categories/:title/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap