# Site Settings
title: Vulcana Cinema
email: vulcanacinema@gmail.com
description: >-
  Vulcana Cinema é uma produtora brasileira focada em cinema de autor, primeiros longas e no mercado internacional.
address: |+
  Rua Castro Alves, 163  
  Porto Alegre, RS — Brasil

baseurl: ""
url: "https://www.vulcanacinema.com"

lang: pt-BR
logo: "/assets/images/logo.png"

collections:
  projects:
    output: true
    permalink: "/:path/"
    
defaults:
  - scope:
      path: ""
    values:
      lang: "pt-BR"
      

# Build settings
markdown: kramdown
permalink: "/:tags/:title/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  name: Vulcana Cinema
  links:
    - https://www.instagram.com/vulcanacinema
    - https://vimeo.com/vulcanacinema
