---
label: Project
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  hidden: true
  default: project
  config:
    required: true
- type: text
  name: title
  label: Title
  config:
    required: true
- name: original_title
  type: text
  config:
    required: false
  label: Original Title
- type: number
  name: release_year
  label: Release Year
- type: file
  name: image
  label: Featured Image
- type: text
  name: trailer
  label: Trailer
- type: field_group
  name: video
  label: Cover Video
  fields:
  - name: mp4
    type: file
    config:
      maxSize: 10
    label: MP4 video file
    description: You can use a GIPHY-generated file.
  - name: gif
    type: file
    config:
      maxSize: 5
    label: GIF file
    description: You can use a GIPHY-generated file.
pages:
- _projects/curtas/deserto-estrangeiro.md
- _projects/curtas/linda-uma-historia-horrivel.md
- _projects/curtas/metade-homem-metade-fantasma.md
- _projects/curtas/o-teto-sobre-nos.md
- _projects/curtas/princesa-morta-do-jacui.md
- _projects/curtas/um-corpo-feminino.md
- _projects/curtas/vida-como-rizoma.md
- _projects/longas/castanha.md
- _projects/longas/o-ultimo-poema.md
- _projects/longas/sobre-sete-ondas-verdes-espumantes.md
- _projects/projetos/5-casas.md
- _projects/tv/o-ninho.md
