---
label: Project
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  hidden: true
  default: project
  config:
    required: true
- type: text
  name: title
  label: Title
  config:
    required: true
- name: original_title
  type: text
  config:
    required: false
  label: Original Title
- type: number
  name: release_year
  label: Release Year
- type: file
  name: image
  label: Featured Image
- type: text
  name: trailer
  label: Trailer
- type: field_group
  name: video
  label: Cover Video
  fields:
  - type: text
    name: mp4
    label: MP4 file
    description: You can use GIPHY-generated MP4.
    config:
      required: false
  - name: gif
    type: file
    config:
      maxSize: 2
    label: GIF file
    description: You can use a GIPHY-generated file.
pages:
- _projects/tv/o-ninho.md
